bcook254/apex-legends-cache

r5apex.dxvk-cache
apex-local.dxvk-cache
Merging files r5apex.dxvk-cache r5apex-local.dxvk-cache
Merging r5apex.dxvk-cache (1/2)... 25015 new entries
Merging r5apex-local.dxvk-cache (2/2)... 42 new entries
Writing 25057 entries to file output.dxvk-cache
Finished
so 42 new entries? :D
=> 1652298429

r5apex.dxvk-cache
Added 1201 entries. Thank you [@harzival](https://github.com/harzival)
=> Contrubtion by harzival

r5apex.dxvk-cache
=> 1652523800

r5apex.dxvk-cache
Added 801 new entries (mostly for world's edge)
=> 1652572120

r5apex.dxvk-cache
Merging files r5apex.dxvk-cache r5apex-local.dxvk-cache
Merging r5apex.dxvk-cache (1/2)... 28668 new entries
Merging r5apex-local.dxvk-cache (2/2)... 467 new entries
Writing 29135 entries to file output.dxvk-cache
Finished
=> DXVK Shaders Pull Request Apex Legend

r5apex.dxvk-cache
555 new entries from @deep2p4ce.
=> 1652819125

r5apex.dxvk-cache
Finally I'm do it after the first mess in my commits :D
Merging files r5apex(1).dxvk-cache r5apex.dxvk-cache
Merging r5apex(1).dxvk-cache (1/2)... 29843 new entries
Merging r5apex.dxvk-cache (2/2)... 184 new entries
Writing 30027 entries to file output.dxvk-cache
Finished
=> 1652954836/184 new, 30027 total

r5apex.dxvk-cache
Re-merge #37 after #36
Merging files r5apex.dxvk-cache incoming.dxvk-cache
Merging r5apex.dxvk-cache (1/2)... 30027 new entries
Merging incoming.dxvk-cache (2/2)... 37 new entries
Writing 30064 entries to file output.dxvk-cache
Finished
Thank you for your contribution @deep2p4ce.
=> 1652978548

r5apex.dxvk-cache
Re-merge #35 after #38
Merging files r5apex.dxvk-cache pull35.dxvk-cache
Merging r5apex.dxvk-cache (1/2)... 30064 new entries
Merging pull35.dxvk-cache (2/2)... 4 new entries
Writing 30068 entries to file output.dxvk-cache
Finished
Thank you for your contribution [@imrmnabil](https://github.com/imrmnabil)
=> 1652979245

r5apex.dxvk-cache
Update from my own cache state file.
=> 1652979631

r5apex.dxvk-cache
Here's another 479 entries.
```log       
Merging files r5apex.dxvk-cache r5apex-local.dxvk-cache
Merging r5apex.dxvk-cache (1/2)... 30102 new entries
Merging r5apex-local.dxvk-cache (2/2)... 479 new entries
Writing 30581 entries to file output.dxvk-cache
Finished
[main a8fe96e] 1653342915
1 file changed, 2 insertions(+), 2 deletions(-)
```
=> 1653342915

r5apex.dxvk-cache
Sorry for my long update for this PR, should now use LFS
Merging files r5apex-git.dxvk-cache r5apex-local.dxvk-cache
Merging r5apex-git.dxvk-cache (1/2)... 30581 new entries
Merging r5apex-local.dxvk-cache (2/2)... 316 new entries
Writing 30897 entries to file output.dxvk-cache
Finished
=> 1653645331

README.md
Added a mention for @TheMethodicalJosh in README.md and their automatic download script found at [TheMethodicalJosh/apex-legends-cache-automated](https://github.com/TheMethodicalJosh/apex-legends-cache-automated)
=> Add TheMethodicalJosh/apex-legends-cache-automated mention

README.md, r5apex.dxvk-cache
Re-merge of #50 (git-lfs not correctly setup)
=> 1654700938

r5apex.dxvk-cache
Merge from #49
Merging files r5apex.dxvk-cache issue49.dxvk-cache
Merging r5apex.dxvk-cache (1/2)... 31186 new entries
Merging issue49.dxvk-cache (2/2)... 656 new entries
Writing 31842 entries to file r5apex.dxvk-cache
Finished
=> 1654701143

r5apex.dxvk-cache
=> 1656096721

r5apex.dxvk-cache
268 new entries
> Merging files r5apex.dxvk-cache r5apex-local.dxvk-cache
> Detected state cache version v10
> Merging r5apex.dxvk-cache (1/2)... 6436 new entries
> Merging r5apex-local.dxvk-cache (2/2)... 268 new entries
> Writing 6704 entries to file output.dxvk-cache
> Finished
=> 1656346672 - 268 new entries

README.md, r5apex.dxvk-cache
Detected state cache version 10
Merging r5apex.dxvk-cache (1/2)... 6995 new entries
Merging xPakrikx.dxvk-cache (2/2)... 409 new entries
Writing 7404 entries to output.dxvk-cache
Finished!
=> 1656511769

README.md, r5apex.dxvk-cache
Detected state cache version 10
Merging r5apex.dxvk-cache (1/2)... 7713 new entries
Merging maxxnino.dxvk-cache (2/2)... 249 new entries
Writing 7962 entries to r5apex.dxvk-cache
Finished!
=> 1657246900

README.md, r5apex.dxvk-cache
Merged entries from @bagusnl. Thank you for your contribution!
Merging r5apex.dxvk-cache (1/2)... 8766 new entries
Merging bagusnl.dxvk-cache (2/2)... 45 new entries
Writing 8811 entries to r5apex.dxvk-cache
Finished!
=> 1660142983

r5apex.dxvk-cache
Thank you @deep2p4ce for your contribution! Merged.
Merging r5apex.dxvk-cache (1/2)... 9088 new entries
Merging deep2p4ce.dxvk-cache (2/2)... 317 new entries
Writing 9405 entries to r5apex.dxvk-cache
Finished!
=> 1660233854

r5apex.dxvk-cache
=> 1660250672

r5apex.dxvk-cache
=> 1660492047

r5apex.dxvk-cache
Merging r5apex.dxvk-cache (1/2)... 11132 new entries
Merging bcook254.dxvk-cache (2/2)... 579 new entries
Writing 11711 entries to r5apex.dxvk-cache
Finished!
=> 1660492890

r5apex.dxvk-cache
Merging r5apex.dxvk-cache (1/2)... 11746 new entries
Merging bcook254.dxvk-cache (2/2)... 70 new entries
Writing 11816 entries to r5apex.dxvk-cache
Finished!
=> 1660840953

README.md, r5apex.dxvk-cache
Thank you for your contribution @Scarlett! Merged.
Merging r5apex.dxvk-cache (1/2)... 11898 new entries
Merging scarlett.dxvk-cache (2/2)... 570 new entries
Writing 12468 entries to r5apex.dxvk-cache
Finished!
=> 1661258936

README.md
Easy to follow, hard to mess up
=> Include a basic single-line installation guide

r5apex.dxvk-cache
=> 1663766679

README.md, r5apex.dxvk-cache
Merging r5apex.dxvk-cache (1/2)... 3368 new entries
Merging whayme.dxvk-cache (2/2)... 12009 new entries
Writing 15377 entries to r5apex.dxvk-cache
Finished!
=> 1663791718

r5apex.dxvk-cache
Thank you @Nightails for you contribution! Merged.
Merging r5apex.dxvk-cache (1/2)... 15377 new entries
Merging nightails.dxvk-cache (2/2)... 920 new entries
Writing 16297 entries to r5apex.dxvk-cache
Finished!
=> 1663792426

README.md, r5apex.dxvk-cache
Thank you for your contribution @Whayme!
Merging r5apex.dxvk-cache (1/2)... 16297 new entries
Merging whayme.dxvk-cache (2/2)... 113 new entries
Writing 16410 entries to r5apex.dxvk-cache
Finished!
=> 1663817064

r5apex.dxvk-cache
Merging r5apex.dxvk-cache (1/2)... 16410 new entries
Merging bcook254.dxvk-cache (2/2)... 48 new entries
Writing 16458 entries to r5apex.dxvk-cache
Finished!
=> 1663817246

r5apex.dxvk-cache
Merging r5apex.dxvk-cache (1/2)... 16528 new entries
Merging bcook254.dxvk-cache (2/2)... 965 new entries
Writing 17493 entries to r5apex.dxvk-cache
Finished!
Added entries from Olympus After Dark Shadow Royale
=> 1664920815

README.md, r5apex.dxvk-cache
Merging r5apex.dxvk-cache (1/2)... 17493 new entries
Merging whayme.dxvk-cache (2/2)... 153 new entries
Writing 17646 entries to r5apex.dxvk-cache
Finished!
=> 1665250591

r5apex.dxvk-cache
Merging r5apex.dxvk-cache (1/2)... 17646 new entries
Merging bcook254.dxvk-cache (2/2)... 98 new entries
Writing 17744 entries to r5apex.dxvk-cache
Finished!
=> 1665250721

README.md, r5apex.dxvk-cache
Merging r5apex.dxvk-cache (1/2)... 17744 new entries
Merging NotTheTime.dxvk-cache (2/2)... 5 new entries
Writing 17749 entries to r5apex.dxvk-cache
Finished!
=> 1665951208

README.md, r5apex.dxvk-cache
Merging r5apex.dxvk-cache (1/2)... 17749 new entries
Merging SohamMalakar.dxvk-cache (2/2)... 703 new entries
Writing 18452 entries to r5apex.dxvk-cache
Finished!
=> 1666225283

README.md, r5apex.dxvk-cache
Merging r5apex.dxvk-cache (1/2)... 3144 new entries
Merging RMED24.dxvk-cache (2/2)... 845 new entries
Writing 3989 entries to r5apex.dxvk-cache
Finished!
=> 1667873435

README.md, r5apex.dxvk-cache
Merging r5apex.dxvk-cache (1/2)... 3989 new entries
Merging Nightails.dxvk-cache (2/2)... 570 new entries
Writing 4559 entries to r5apex.dxvk-cache
Finished!
=> 1668019840
